[assembly: System.Reflection.AssemblyTitle("Sensor Readout")]
[assembly: System.Reflection.AssemblyDescription("Accessible hardware sensor and device readout")]
[assembly: System.Reflection.AssemblyProduct("Sensor Readout")]
[assembly: System.Reflection.AssemblyCompany("Andre Louis")]
[assembly: System.Reflection.AssemblyCopyright("Copyright (c) Andre Louis and Sensor Readout contributors")]
[assembly: System.Reflection.AssemblyVersion("4.1.0.0")]
[assembly: System.Reflection.AssemblyFileVersion("4.1.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersion("4.1.0.0")]
